name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        msbuild-version: 16.0
        
    - name: Install WiX Toolset v3.11
      run: |
        New-Item -ItemType Directory -Path "C:\wix311"
        Invoke-WebRequest -Uri "https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311.exe" -OutFile "C:\wix311\wix311.exe"
        Start-Process -Wait -FilePath "C:\wix311\wix311.exe" -ArgumentList "/install /quiet"

    - name: Restore NuGet packages
      run: nuget restore FaineSwitcher/FaineSwitcher.sln

    - name: Build FaineSwitcher project
      run: msbuild.exe FaineSwitcher/FaineSwitcher.csproj /p:Configuration=Release /p:OutputPath=bin/FaineSwitcher
  
    - name: Build FaineSwitcherSetup project
      run: |
          cd FaineSwitcherSetup
          msbuild.exe FaineSwitcherSetup.wixproj /p:Configuration=Release
          
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        body: |
          Automatic build and release of FaineSwitcher and FaineSwitcherSetup projects
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: xresloader/upload-to-github-release@v1
      with:
        files: |
          FaineSwitcherSetup/bin/Release/FaineSwitcherSetup.msi
        token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
        owner: ${{ github.repository_owner }}
        repo: ${{ github.event.repository.name }}
        tag: v${{ github.run_number }}
        overwrite: true
