name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        msbuild-version: 16.0

    - name: Restore NuGet packages
      run: nuget restore FaineSwitcher/FaineSwitcher.sln

    - name: Build FaineSwitcher project
      run: msbuild.exe FaineSwitcher/FaineSwitcher.csproj /p:Configuration=Release /p:OutputPath=bin/FaineSwitcher

    - name: Build FaineSwitcherSetup project
      run: msbuild.exe FaineSwitcherSetup/FaineSwitcherSetup.csproj /p:Configuration=Release /p:OutputPath=bin/FaineSwitcherSetup /p:SelfContained=true /p:RuntimeIdentifier=win-x64

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        body: |
          Automatic build and release of FaineSwitcher and FaineSwitcherSetup projects
        draft: false
        prerelease: false

    - name: Upload FaineSwitcher binaries
      uses: actions/upload-artifact@v1
      with:
        name: FaineSwitcher
        path: bin/FaineSwitcher

    - name: Upload FaineSwitcherSetup binaries
      uses: actions/upload-artifact@v1
      with:
        name: FaineSwitcherSetup
        path: bin/FaineSwitcherSetup

